const COUNTRY_MAP = {
  // Africa
  nigeria: "NG",
  nigerian: "NG",
  kenya: "KE",
  kenyan: "KE",
  ghana: "GH",
  ghanaian: "GH",
  "south africa": "ZA",
  "south african": "ZA",
  ethiopia: "ET",
  ethiopian: "ET",
  tanzania: "TZ",
  tanzanian: "TZ",
  uganda: "UG",
  ugandan: "UG",
  angola: "AO",
  angolan: "AO",
  cameroon: "CM",
  cameroonian: "CM",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  senegal: "SN",
  senegalese: "SN",
  mali: "ML",
  malian: "ML",
  "burkina faso": "BF",
  niger: "NE",
  nigerien: "NE",
  benin: "BJ",
  beninese: "BJ",
  togo: "TG",
  togolese: "TG",
  guinea: "GN",
  guinean: "GN",
  "guinea-bissau": "GW",
  "sierra leone": "SL",
  liberia: "LR",
  liberian: "LR",
  gambia: "GM",
  "the gambia": "GM",
  "cape verde": "CV",
  "cabo verde": "CV",
  mauritania: "MR",
  mauritanian: "MR",
  morocco: "MA",
  moroccan: "MA",
  algeria: "DZ",
  algerian: "DZ",
  tunisia: "TN",
  tunisian: "TN",
  libya: "LY",
  libyan: "LY",
  egypt: "EG",
  egyptian: "EG",
  sudan: "SD",
  sudanese: "SD",
  "south sudan": "SS",
  somalia: "SO",
  somali: "SO",
  djibouti: "DJ",
  eritrea: "ER",
  eritrean: "ER",
  rwanda: "RW",
  rwandan: "RW",
  burundi: "BI",
  burundian: "BI",
  mozambique: "MZ",
  mozambican: "MZ",
  zambia: "ZM",
  zambian: "ZM",
  zimbabwe: "ZW",
  zimbabwean: "ZW",
  malawi: "MW",
  malawian: "MW",
  botswana: "BW",
  namibia: "NA",
  namibian: "NA",
  lesotho: "LS",
  eswatini: "SZ",
  swaziland: "SZ",
  madagascar: "MG",
  malagasy: "MG",
  mauritius: "MU",
  mauritian: "MU",
  seychelles: "SC",
  comoros: "KM",
  comorian: "KM",
  "democratic republic of the congo": "CD",
  drc: "CD",
  "dr congo": "CD",
  "republic of the congo": "CG",
  congo: "CG",
  gabon: "GA",
  gabonese: "GA",
  "equatorial guinea": "GQ",
  "central african republic": "CF",
  chad: "TD",
  chadian: "TD",
  "sao tome and principe": "ST",
  "western sahara": "EH",
  // Rest of world
  "united states": "US",
  usa: "US",
  america: "US",
  american: "US",
  "united kingdom": "GB",
  uk: "GB",
  britain: "GB",
  england: "GB",
  british: "GB",
  canada: "CA",
  canadian: "CA",
  australia: "AU",
  australian: "AU",
  germany: "DE",
  german: "DE",
  france: "FR",
  french: "FR",
  italy: "IT",
  italian: "IT",
  spain: "ES",
  spanish: "ES",
  portugal: "PT",
  portuguese: "PT",
  netherlands: "NL",
  dutch: "NL",
  brazil: "BR",
  brazilian: "BR",
  china: "CN",
  chinese: "CN",
  japan: "JP",
  japanese: "JP",
  india: "IN",
  indian: "IN",
  russia: "RU",
  russian: "RU",
  mexico: "MX",
  mexican: "MX",
  argentina: "AR",
  argentinian: "AR",
  colombia: "CO",
  colombian: "CO",
  indonesia: "ID",
  indonesian: "ID",
  pakistan: "PK",
  pakistani: "PK",
  bangladesh: "BD",
  bangladeshi: "BD",
  philippines: "PH",
  filipino: "PH",
  vietnam: "VN",
  vietnamese: "VN",
  thailand: "TH",
  thai: "TH",
  turkey: "TR",
  turkish: "TR",
  iran: "IR",
  iranian: "IR",
  "saudi arabia": "SA",
  saudi: "SA",
};

function lookupCountryCode(name) {
  if (!name) return null;
  return COUNTRY_MAP[name.trim().toLowerCase()] || null;
}

module.exports = { COUNTRY_MAP, lookupCountryCode };
